# Generated by Django 5.2.4 on 2025-07-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.CharField(default='Not specified', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(default='None', help_text='Comma-separated interests'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(default='Not specified', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
